# Sports Prediction Platform - Installation Package Creator
# Creates standalone executable with PyInstaller

"""
Installation Package Builder
Creates a standalone Windows executable for the Sports Prediction Platform
"""

import PyInstaller.__main__
from pathlib import Path
import shutil
import os

# Project root
PROJECT_ROOT = Path(__file__).parent
DIST_DIR = PROJECT_ROOT / "dist"
BUILD_DIR = PROJECT_ROOT / "build"

def clean_build_dirs():
    """Clean previous build artifacts"""
    print("🧹 Cleaning previous builds...")
    for dir_path in [DIST_DIR, BUILD_DIR]:
        if dir_path.exists():
            shutil.rmtree(dir_path)
    print("✓ Build directories cleaned")

def create_executable():
    """Create standalone executable"""
    print("\n📦 Building executable...")
    print("=" * 60)
    
    # PyInstaller options
    options = [
        'main.py',  # Entry point
        '--name=SportsPredictor',
        '--onefile',  # Single executable
        '--windowed',  # No console window (for GUI)
        '--icon=NONE',  # Add icon if you have one
        
        # Include data files
        '--add-data=src;src',
        '--add-data=LL9_4_DOMAIN_AWARE_MODELS_AND_WEIGHTS_WITH_SHAP;LL9_4_DOMAIN_AWARE_MODELS_AND_WEIGHTS_WITH_SHAP',
        '--add-data=datasets;datasets',
        
        # Hidden imports (modules not auto-detected)
        '--hidden-import=sklearn.utils._weight_vector',
        '--hidden-import=sklearn.neighbors._typedefs',
        '--hidden-import=sklearn.neighbors._partition_nodes',
        '--hidden-import=sklearn.tree._utils',
        '--hidden-import=catboost',
        '--hidden-import=lightgbm',
        '--hidden-import=xgboost',
        '--hidden-import=pandas',
        '--hidden-import=numpy',
        '--hidden-import=scipy',
        '--hidden-import=streamlit',
        '--hidden-import=plotly',
        '--hidden-import=reportlab',
        
        # Exclude unnecessary modules
        '--exclude-module=PyQt6',  # GUI optional
        '--exclude-module=tkinter',
        '--exclude-module=matplotlib',
        '--exclude-module=IPython',
        
        # Performance
        '--optimize=2',
        '--strip',  # Remove debug symbols
        
        # Output
        f'--distpath={DIST_DIR}',
        f'--workpath={BUILD_DIR}',
        '--clean',
    ]
    
    print("Building with PyInstaller...")
    print("This may take 5-10 minutes...")
    
    try:
        PyInstaller.__main__.run(options)
        print("\n✅ Build successful!")
        print(f"\nExecutable location: {DIST_DIR / 'SportsPredictor.exe'}")
        print(f"Size: {(DIST_DIR / 'SportsPredictor.exe').stat().st_size / (1024*1024):.1f} MB")
        return True
    except Exception as e:
        print(f"\n❌ Build failed: {e}")
        return False

def create_installer_script():
    """Create NSIS installer script (requires NSIS installed)"""
    print("\n📝 Creating installer script...")
    
    nsis_script = '''
; Sports Prediction Platform Installer
; Generated by PyInstaller build script

!include "MUI2.nsh"

Name "Sports Prediction Platform"
OutFile "SportsPredictor_Setup.exe"
InstallDir "$PROGRAMFILES\\SportsPredictor"
RequestExecutionLevel admin

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "LICENSE"
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_LANGUAGE "English"

Section "Install"
    SetOutPath "$INSTDIR"
    
    ; Copy main executable
    File "dist\\SportsPredictor.exe"
    
    ; Copy data folders
    SetOutPath "$INSTDIR\\LL9_4_DOMAIN_AWARE_MODELS_AND_WEIGHTS_WITH_SHAP"
    File /r "LL9_4_DOMAIN_AWARE_MODELS_AND_WEIGHTS_WITH_SHAP\\*.*"
    
    SetOutPath "$INSTDIR\\datasets"
    File /r "datasets\\*.*"
    
    ; Create shortcuts
    CreateDirectory "$SMPROGRAMS\\Sports Predictor"
    CreateShortcut "$SMPROGRAMS\\Sports Predictor\\Sports Predictor.lnk" "$INSTDIR\\SportsPredictor.exe"
    CreateShortcut "$DESKTOP\\Sports Predictor.lnk" "$INSTDIR\\SportsPredictor.exe"
    
    ; Create uninstaller
    WriteUninstaller "$INSTDIR\\Uninstall.exe"
    CreateShortcut "$SMPROGRAMS\\Sports Predictor\\Uninstall.lnk" "$INSTDIR\\Uninstall.exe"
    
    ; Registry entries
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\SportsPredictor" "DisplayName" "Sports Prediction Platform"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\SportsPredictor" "UninstallString" "$INSTDIR\\Uninstall.exe"
SectionEnd

Section "Uninstall"
    Delete "$INSTDIR\\SportsPredictor.exe"
    Delete "$INSTDIR\\Uninstall.exe"
    RMDir /r "$INSTDIR\\LL9_4_DOMAIN_AWARE_MODELS_AND_WEIGHTS_WITH_SHAP"
    RMDir /r "$INSTDIR\\datasets"
    RMDir "$INSTDIR"
    
    Delete "$SMPROGRAMS\\Sports Predictor\\*.*"
    RMDir "$SMPROGRAMS\\Sports Predictor"
    Delete "$DESKTOP\\Sports Predictor.lnk"
    
    DeleteRegKey HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\SportsPredictor"
SectionEnd
'''
    
    installer_script = PROJECT_ROOT / "installer.nsi"
    with open(installer_script, 'w') as f:
        f.write(nsis_script)
    
    print(f"✓ Installer script created: {installer_script}")
    print("\nTo create installer:")
    print("1. Install NSIS: https://nsis.sourceforge.io/Download")
    print(f"2. Run: makensis {installer_script}")

def create_portable_package():
    """Create portable ZIP package"""
    print("\n📦 Creating portable package...")
    
    portable_dir = PROJECT_ROOT / "portable"
    if portable_dir.exists():
        shutil.rmtree(portable_dir)
    
    portable_dir.mkdir()
    
    # Copy executable
    shutil.copy(DIST_DIR / "SportsPredictor.exe", portable_dir)
    
    # Copy essential data
    shutil.copytree("LL9_4_DOMAIN_AWARE_MODELS_AND_WEIGHTS_WITH_SHAP", 
                    portable_dir / "LL9_4_DOMAIN_AWARE_MODELS_AND_WEIGHTS_WITH_SHAP")
    shutil.copytree("datasets", portable_dir / "datasets")
    
    # Create README
    readme = '''
Sports Prediction Platform - Portable Edition

QUICK START:
1. Double-click SportsPredictor.exe
2. Activate with license key (or use trial)
3. Select sport (NHL, NFL, NBA, MLB)
4. View predictions and analytics

FEATURES:
- AI-powered win/loss predictions (55%+ accuracy)
- Real-time odds integration (API-Sports)
- Advanced analytics dashboard
- PDF/CSV report export
- SHAP explainability

SYSTEM REQUIREMENTS:
- Windows 10/11 (64-bit)
- 4GB RAM minimum
- 1GB free disk space

SUPPORT:
- Documentation: See docs folder
- Generate license: Run generate_license_key.py
- API setup: Create .env file with APISPORTS_KEY=your_key

VERSION: 1.0.0
'''
    
    with open(portable_dir / "README.txt", 'w') as f:
        f.write(readme)
    
    # Create ZIP
    shutil.make_archive('SportsPredictor_Portable', 'zip', portable_dir)
    
    print(f"✓ Portable package created: SportsPredictor_Portable.zip")
    print(f"   Size: {Path('SportsPredictor_Portable.zip').stat().st_size / (1024*1024):.1f} MB")

def main():
    """Main build process"""
    print("=" * 60)
    print("SPORTS PREDICTION PLATFORM - INSTALLATION PACKAGE BUILDER")
    print("=" * 60)
    print()
    
    # Step 1: Clean
    clean_build_dirs()
    
    # Step 2: Create executable
    if not create_executable():
        print("\n❌ Build failed. Please check errors above.")
        return
    
    # Step 3: Create installer script
    create_installer_script()
    
    # Step 4: Create portable package
    create_portable_package()
    
    print("\n" + "=" * 60)
    print("✅ BUILD COMPLETE!")
    print("=" * 60)
    print("\nDeliverable packages:")
    print(f"  1. Executable: {DIST_DIR / 'SportsPredictor.exe'}")
    print(f"  2. Portable ZIP: SportsPredictor_Portable.zip")
    print(f"  3. Installer script: installer.nsi (requires NSIS)")
    print()
    print("Distribution options:")
    print("  - Send SportsPredictor_Portable.zip (easiest)")
    print("  - Send standalone .exe (requires models folder)")
    print("  - Create .exe installer with NSIS (most professional)")
    print()

if __name__ == "__main__":
    # Note: This script requires pyinstaller installed
    # Install with: pip install pyinstaller
    
    try:
        main()
    except Exception as e:
        print(f"\n❌ Error: {e}")
        print("\nMake sure PyInstaller is installed:")
        print("  pip install pyinstaller")
